[project]
name = "minimal-devenv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "auglib>=1.0.4",
    "autrainer==0.6.0",
    "cowsay>=6.1",
    "hear21passt>=0.0.26",
    "pydub>=0.25.1",
]

[tool.uv]
dev-dependencies = ["ruff", "rich"]
