id: CoarseNet-32k-ML-Balanced-qwen
_target_: BalancedSamplingDataset.BalancedSamplingDataset

path: /path/to/EDANSA-2019 
features_subdir: data
index_column: Clip Path

target_column: ['Anth', 'Bio', 'Geo', 'Sil']
file_type: wav
file_handler: 
  autrainer.datasets.utils.AudioFileHandler:
    target_sample_rate: 16000

criterion: torch.nn.BCEWithLogitsLoss
metrics:
  - autrainer.metrics.MLAccuracy
  - autrainer.metrics.MLF1Macro
  - autrainer.metrics.MLF1Micro
  - autrainer.metrics.MLF1Weighted
tracking_metric: autrainer.metrics.MLF1Macro

transform:
  type: raw